### ISSUE TITLE
342 dimension in g3d data 

### ISSUE THREAD

**Issue by BehnooshParsa** [p0werHu/Lie-NET#1]
Hi,

In the code, it is mentioned that 342 = A*2(19) as we have 19 bones 2 rotation matric for each and A samples. How did you create those samples? 

I wan to run this code for other datasets and I am wondering how I can generate such data.

Thank you.

**Comment by Ai-is-light** [comment]
the same problem

**Comment by hjf1997** [comment]
> Hi,
> 
> In the code, it is mentioned that 342 = A*2(19) as we have 19 bones 2 rotation matric for each and A samples. How did you create those samples?
> 
> I wan to run this code for other datasets and I am wondering how I can generate such data.
> 
> Thank you.

Hello, github didn't inform me this issue. So, sorry for the late. You could use the code provided by [http://ravitejav.weebly.com/kbac.html](http://ravitejav.weebly.com/kbac.html) In the paper, the author described how to map locations of joints to Lie group representation.

**Comment by Ai-is-light** [comment]
@p0werHu would you mind sharing your pre-trained model, I would like to compare with the model trained by myself.
Thanks

**Comment by hjf1997** [comment]
> @p0werHu would you mind sharing your pre-trained model, I would like to compare with the model trained by myself.
> Thanks

Sorry, I have deleted the pre-trained model. But, in fact, I remember that I nearly reproduced the result reported in the paper. I am outside these days. If you need that, I can provide you that after 10/5.
PS: I didn't write the restore function in my code. So if you want to use my code to load pre-trained model, you need implement that. It's very easy by pytorch.
For more detials about the mode, you could read the original paper.
